export const SET_LOADING = "SET_LOADING";
export const AJOUT_TASK_SUCCESS = "AJOUT_TASK_SUCCESS";
export const AJOUT_FAIL = "AJOUT_FAIL";
export const GET_ALL_TASK_SUCCESS="GET_ALL_TASK_SUCCESS";
export const DELETE_TASK_SUCCESS="DELETE_TASK_SUCCESS";


